#ifndef HAMMIXER_VERSION_H
#define HAMMIXER_VERSION_H

#define HAMMIXER_VERSION_MAJOR 1
#define HAMMIXER_VERSION_MINOR 3
#define HAMMIXER_VERSION_PATCH 0
#define HAMMIXER_VERSION_STRING "1.3"
#define HAMMIXER_VERSION_DATE "27Jan2026"

#define HAMMIXER_APP_NAME "HamMixer CT7BAC :: IC7300 + WebSDR Mixer"
#define HAMMIXER_WEBSDR_NAME "HamMixer CT7BAC :: WebSDR Viewer"
#define HAMMIXER_ORG_NAME "HamMixer"
#define HAMMIXER_ORG_DOMAIN "hammixer.local"

#endif // HAMMIXER_VERSION_H
