#ifndef HAMMIXER_VERSION_H
#define HAMMIXER_VERSION_H

#define HAMMIXER_VERSION_MAJOR 1
#define HAMMIXER_VERSION_MINOR 5
#define HAMMIXER_VERSION_PATCH 0
#define HAMMIXER_VERSION_STRING "1.5"
#define HAMMIXER_VERSION_DATE "01Feb2026"

#define HAMMIXER_APP_NAME "HamMixer CT7BAC :: Transceiver + WebSDR Mixer"
#define HAMMIXER_WEBSDR_NAME "HamMixer CT7BAC :: WebSDR Viewer"
#define HAMMIXER_ORG_NAME "HamMixer"
#define HAMMIXER_ORG_DOMAIN "hammixer.local"

#endif // HAMMIXER_VERSION_H
